version: '2'

services:
  pihole:
    extends:
      service: pihole
      file: pihole/docker-compose.yaml
    networks:
      home:
        ipv4_address: 192.168.11.161
     
networks:
  home:
    driver: macvlan
    driver_opts:
      parent: ovs_eth0
    ipam:
      config:
        - subnet: 192.168.11.0/24
          gateway: 192.168.11.254
          ip_range: 192.168.11.160/28
