version: '3.8'

services:
  qbittorrent:
    container_name: qbittorrent-1
    image: binhex/arch-qbittorrentvpn:latest
    hostname: qbit
    domainname: thelauerfamily.us
    cap_add:
      - NET_ADMIN
    networks:
      - home
    ports:
      - 22877/tcp
      - 22877/udp
      - 8080/tcp
      - 8118/tcp
    environment:
      TZ: 'Asia/Singapore'
      ENABLE_PRIVOXY: "yes"
      HOME: "/home/nobody"
      LAN_NETWORK: 192.168.11.0/24
      NAME_SERVERS: 1.1.1.1,1.0.0.1
      STRICT_PORT_FORWARD: "yes"
      VPN_ENABLED: "yes"
      VPN_PROV: airvpn
      WEBUI_PORT: 8080
    volumes:
      - /volume1/Media:/Media:rw
      - /volume1/docker/qbittorrentvpn/config:/config:rw
    restart: always
