version: '3.9'

services:
  qbittorrent:
    extends:
      service: qbittorrent
      file: plex/docker-compose.yaml
  sabnzbd:
    extends:
      service: sabnzbd
      file: plex/docker-compose.yaml
  plex:
    extends:
      service: plex
      file: plex/docker-compose.yaml
  bazarr:
    extends:
      service: bazarr
      file: plex/docker-compose.yaml
  sonarr:
    extends:
      service: sonarr
      file: plex/docker-compose.yaml
  radarr:
    extends:
      service: radarr
      file: plex/docker-compose.yaml
  readarr:
    extends:
      service: readarr
      file: plex/docker-compose.yaml
    deploy:
      resources:
        limits:
          memory: 1g    
  prowlarr:
    extends:
      service: prowlarr
      file: plex/docker-compose.yaml
  overseerr:
    extends:
      service: overseerr
      file: plex/docker-compose.yaml
  tautulli:
    extends:
      service: tautulli
      file: plex/docker-compose.yaml
  # calibre:
  #   extends:
  #     service: calibre
  #     file: plex/docker-compose.yaml

networks:
  default:
    name: Plex
    external: true
