version: '2'

services:
  pihole:
    extends:
      service: pihole
      file: pihole/docker-compose.yaml
    networks:
      home:
        ipv4_address: 192.168.11.253
  qbittorrent:
    extends:
      service: qbittorrent
      file: plex/docker-compose.yaml
  plex:
    extends:
      service: plex
      file: plex/docker-compose.yaml

networks:
  home:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.11.0/24
          gateway: 192.168.11.1
          ip_range: 192.168.11.192/26
  Plex:
    external:
      name: Plex
  bridge:
    external:
      name: Bridge
