version: '2'

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    hostname: plex
    domainname: thelauerfamily.us
    network_mode: "host"
    environment:
      TZ: 'Asia/Singapore'
      HOME: '/config'
      CHANGE_CONFIG_DIR_OWNERSHIP: 'true'
    volumes:
      - /volume1/docker/plex:/config:rw
      - /volume1/Media/Library/Movies:/mnt/movies:rw
      - /volume1/Media/Library/TVShows:/mnt/tvshows:rw
      - /tmp:/transcode:rw
    restart: always

  qbittorrent:
    container_name: qbittorrent-1
    image: binhex/arch-qbittorrentvpn:latest
    hostname: qbit
    domainname: thelauerfamily.us
    networks:
      - Plex
    ports:
      - "22877:22877/tcp"
      - "22877:22877/udp"
      - "8080:8080/tcp"
      - "8118:8118/udp"
    environment:
      TZ: 'Asia/Singapore'
      ENABLE_PRIVOXY: "yes"
      HOME: "/home/nobody"
      LAN_NETWORK: 192.168.11.0/24
      NAME_SERVERS: 1.1.1.1,1.0.0.1
      STRICT_PORT_FORWARD: "yes"
      VPN_ENABLED: "yes"
      VPN_PROV: airvpn
      WEBUI_PORT: 8080
    volumes:
      - /volume1/Media:/Media:rw
      - /volume1/docker/qbittorrentvpn/config:/config:rw
    restart: always
