version: '2'

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    hostname: plex
    domainname: thelauerfamily.us
    network_mode: "host"
    environment:
      TZ: 'Asia/Singapore'
      HOME: '/config'
      CHANGE_CONFIG_DIR_OWNERSHIP: 'true'
    volumes:
      - /volume1/docker/plex:/config:rw
      - /volume1/Media/Library/Movies:/mnt/movies:rw
      - /volume1/Media/Library/TVShows:/mnt/tvshows:rw
      - /tmp:/transcode:rw
    restart: always
    labels:
      - "traefik.enable=false"
  nzbget:
    container_name: nzbget
    image: hotio/nzbget:latest
    networks:
      - Plex
    ports:
      - "6789:6789"
    environment:
      - PUID=1026
      - PGID=100
      - UMASK=002
      - TZ=Asia/Singapore
    volumes:
      - /volume1/docker/nzbget/config:/config:rw
      - /volume1/Media/Downloads/Usenet:/Media/Downloads/Usenet:rw
    restart: always
    labels:
      - "traefik.enable=false"
  qbittorrent:
    container_name: qbittorrent
    image: binhex/arch-qbittorrentvpn:latest
    hostname: qbit
    domainname: thelauerfamily.us
    cap_add:
      - NET_ADMIN
    networks:
      - Plex
    ports:
      - "22877:22877/tcp"
      - "22877:22877/udp"
      - "18080:18080/tcp"
      - "8118:8118/udp"
    environment:
      TZ: 'Asia/Singapore'
      ENABLE_PRIVOXY: "yes"
      HOME: "/home/nobody"
      LAN_NETWORK: 192.168.11.0/24
      NAME_SERVERS: "1.1.1.1,1.0.0.1"
      STRICT_PORT_FORWARD: "yes"
      VPN_ENABLED: "yes"
      VPN_PROV: airvpn
      WEBUI_PORT: 18080
      UMASK: 000
      PUID: 1026
      PGID: 100
    volumes:
      - /volume1/Media:/Media:rw
      - /volume1/docker/qbittorrentvpn/config:/config:rw
    restart: always
    labels:
      - "traefik.enable=false"
  bazarr:
    container_name: bazarr
    image: cr.hotio.dev/hotio/bazarr:nightly-1.0.3-beta.26
    networks:
      - Plex
    ports:
      - "6767:6767"
    environment:
      - PUID=1026
      - PGID=100
      - UMASK=002
      - TZ=Asia/Singapore
    volumes:
      - /volume1/docker/bazarr/config:/config:rw
      - /volume1/Media:/Media:rw
    restart: always
    labels:
      - "traefik.enable=false"
  sonarr:
    container_name: sonarr
    image: hotio/sonarr:nightly
    networks:
      - Plex
    ports:
      - "8989:8989"
    environment:
      - PUID=1026
      - PGID=100
      - UMASK=002
      - TZ=Asia/Singapore
      - CONFIG_DIR=/config
    volumes:
      - /volume1/docker/sonarr/config:/config:rw
      - /volume1/Media:/Media:rw
    restart: always
    labels:
      - "traefik.enable=false"
  radarr:
    container_name: radarr
    image: hotio/radarr:nightly
    networks:
      - Plex
    ports:
      - "7878:7878"
    environment:
      - PUID=1026
      - PGID=100
      - UMASK=002
      - TZ=Asia/Singapore
      - CONFIG_DIR=/config
    volumes:
      - /volume1/docker/radarr/config:/config:rw
      - /volume1/Media:/Media:rw
    restart: always
    labels:
      - "traefik.enable=false"
  readarr:
    container_name: readarr
    image: hotio/readarr:nightly
    networks:
      - Plex
    ports:
      - "8787:8787"
    environment:
      - PUID=1026
      - PGID=100
      - UMASK=002
      - TZ=Asia/Singapore
      - CONFIG_DIR=/config
    volumes:
      - /volume1/docker/readarr/config:/config:rw
      - /volume1/Media:/Media:rw
    restart: always
    labels:
      - "traefik.enable=false"
  prowlarr:
    container_name: prowlarr
    image: hotio/prowlarr:testing
    networks:
      - Plex
    ports:
      - "9696:9696"
    environment:
      - PUID=1026
      - PGID=100
      - UMASK=002
      - TZ=Asia/Singapore
      - CONFIG_DIR=/config
    volumes:
      - /volume1/docker/prowlarr/config:/config:rw
    restart: always
    labels:
      - "traefik.enable=false"
  overseerr:
    container_name: overseerr
    image:  hotio/overseerr:release
    networks:
      - Plex
    ports:
      - "5055:5055"
    environment:
      - PUID=1026
      - PGID=100
      - UMASK=002
      - TZ=Asia/Singapore
    volumes:
      - /volume1/docker/overseerr/config:/config:rw
    restart: always
    labels:
      - "traefik.enable=false"
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    networks:
      - Plex
    volumes:
      - /volume1/docker/tautulli/config:/config:rw
      - /volume1/docker/plex/Library/Application Support/Plex Media Server/Logs:/mnt/plexlogs:r
    environment:
      - PUID=1026
      - PGID=100
      - UMASK=002
      - TZ=Asia/Singapore
    ports:
      - "8181:8181/tcp"
    labels:
      - "traefik.enable=false"
