version: '2'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    domainname: thelauerfamily.us
    mac_address: 3d:a4:f2:b6:82:36
    cap_add:
      - NET_ADMIN
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    environment:
      ServerIP: 192.168.11.161
      WEBPASSWORD: ""
      VIRTUAL_HOST: pihole.thelauerfamily.us
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
    volumes:
      - /volume1/docker/pihole/volume:/etc/pihole:rw
      - /volume1/docker/pihole/config/hosts:/etc/hosts:ro
      - /volume1/docker/pihole/config/resolv.conf:/etc/resolv.conf:ro
      - /volume1/docker/pihole/config/dnsmasq.conf:/etc/dnsmasq.d/02-network.conf:ro
    restart: always
